model: ""
quantization: "" 
dtype: "" 
huggingface_token : ""

tokens: # Highest priority is more important
  - token: ""
    priority: 1

sender:
  image:
    repository: centralesupelec/aristote-dispatcher-sender
    pullPolicy: IfNotPresent
    tag: latest
  port: 8080
  ressources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  replicaCount: 1
  env: []

consumer:
  image:
    repository: centralesupelec/aristote-dispatcher-consumer
    pullPolicy: IfNotPresent
    tag: latest
  port: 8080
  ressources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  replicaCount: 2
  env: []

inferenceserver:
  image:
    repository: vllm/vllm-openai
    pullPolicy: IfNotPresent
    tag: latest
  port: 8000
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
      nvidia.com/gpu: 1
  env: []
  suffix: /v1/chat/completions

rabbitmq:
  enabled: True
  internal: True
  auth:
    user: ""
    password: ""
  host: ""

database:
  internal: True
  type: mysql
  host: ""
  auth:
    rootPassword: root
    username: user
    password: password
    database: test
  initdbScriptsConfigMap: database-config-map

mysql:
  enabled: True
  auth:
    rootPassword: root
    username: user
    password: password
    database: test
  initdbScriptsConfigMap: database-config-map

postgresql:
  enabled: False
  auth:
    rootPassword: root
    username: user
    password: password
    database: test
  initdbScriptsConfigMap: database-config-map

ingress:
  enabled: True
  className: nginx
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: hostname
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: secret-tls-vllm
    hosts:
       - hostname

# Add nodeSelectors to target specific GPU types
nodeSelector: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}