"""add organization fields to metrics table

Revision ID: 212c4b4d9489
Revises: 5dd94aeafd3c
Create Date: 2025-12-12 13:41:32.530640

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "212c4b4d9489"
down_revision: Union[str, Sequence[str], None] = "5dd94aeafd3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics",
        sa.Column("user_organization", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "metrics",
        sa.Column("server_organization", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics", "server_organization")
    op.drop_column("metrics", "user_organization")
    # ### end Alembic commands ###
