"""decouple tables

Revision ID: 5dd94aeafd3c
Revises: 8e1d058df426
Create Date: 2025-12-12 13:24:26.822013

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dd94aeafd3c"
down_revision: Union[str, Sequence[str], None] = "8e1d058df426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("metrics_user_name_fkey"), "metrics", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("metrics_user_name_fkey"),
        "metrics",
        "users",
        ["user_name"],
        ["name"],
    )
    # ### end Alembic commands ###
