"""add routing mode column to metrics table

Revision ID: 8e1d058df426
Revises: fa7a30b960b4
Create Date: 2025-12-10 11:53:51.852893

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e1d058df426"
down_revision: Union[str, Sequence[str], None] = "fa7a30b960b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics",
        sa.Column("routing_mode", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics", "routing_mode")
    # ### end Alembic commands ###
