"""add routing mode column to metrics table

Revision ID: e073ae55fc3f
Revises: fa7a30b960b4
Create Date: 2025-12-04 18:22:31.149249

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e073ae55fc3f"
down_revision: Union[str, Sequence[str], None] = "fa7a30b960b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics",
        sa.Column(
            "routing_mode",
            sa.Enum("any", "private-first", "private-only", native_enum=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics", "routing_mode")
    # ### end Alembic commands ###
