"""Add fields to Metric entity

Revision ID: fa7a30b960b4
Revises: c63af0f18c5d
Create Date: 2025-09-24 13:14:58.417138

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa7a30b960b4"
down_revision: Union[str, Sequence[str], None] = "c63af0f18c5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metrics", sa.Column("requeue_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "metrics",
        sa.Column("max_parallel_requests", sa.Integer(), nullable=True),
    )
    op.add_column(
        "metrics",
        sa.Column("current_parallel_requests", sa.Integer(), nullable=True),
    )
    op.add_column(
        "metrics", sa.Column("priority", sa.Integer(), nullable=True)
    )
    op.add_column(
        "metrics", sa.Column("strategy", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "metrics", sa.Column("performance_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metrics", "priority")
    op.drop_column("metrics", "current_parallel_requests")
    op.drop_column("metrics", "max_parallel_requests")
    op.drop_column("metrics", "requeue_count")
    op.drop_column("metrics", "strategy")
    op.drop_column("metrics", "performance_score")
    # ### end Alembic commands ###
