apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vllm.fullname" . }}-consumer 
  {{- with .Values.consumer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}   
  labels:
    {{- include "vllm.labels.consumer" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      {{- include "vllm.selectorLabels.consumer" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.consumer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vllm.selectorLabels.consumer" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.consumer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-vllm
          securityContext:
            {{- toYaml .Values.inferenceserver.securityContext | nindent 12 }}
          image: "{{ .Values.inferenceserver.image.repository }}:{{ .Values.inferenceserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.inferenceserver.image.pullPolicy | quote }}
          command:
          - python3
          - -m
          - vllm.entrypoints.openai.api_server
          - --model
          - {{ .Values.model | quote }}
          {{ if not (eq .Values.servedModelName "")}}- --served_model_name={{ .Values.servedModelName }} {{ end }}
          {{ if not (eq .Values.quantization "")}}- --quantization={{ .Values.quantization }} {{ end }}
          {{ if not (eq .Values.dtype "")}}- --dtype={{ .Values.dtype }} {{ end }}
          {{ if not (eq .Values.gpuMemoryUtilization "")}}- --gpu_memory_utilization={{ .Values.gpuMemoryUtilization }} {{ end }}
          - --trust-remote-code
          ports:
            - name: http
              containerPort: {{ .Values.inferenceserver.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 6
            # Allow for up to 10 minutes of startup time
            failureThreshold: 100
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.inferenceserver.resources | nindent 12 }}
          env:
            - name: PORT 
              value: {{ .Values.inferenceserver.port | quote }}
            - name: HF_TOKEN
              value: {{ .Values.huggingface_token | quote }}
            {{- with .Values.inferenceserver.env }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
        - name: {{ .Chart.Name }}-consumer
          securityContext:
            {{- toYaml .Values.consumer.securityContext | nindent 12 }}
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy | quote }}
          livenessProbe:
            exec:
              command:
              - sh
            initialDelaySeconds: 2
            periodSeconds: 30
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
              - sh
            initialDelaySeconds: 2
            periodSeconds: 30
            failureThreshold: 10
          resources:
            {{- toYaml .Values.consumer.resources | nindent 12 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: {{ .Release.Name }}-consumer
            - name: TARGET_PORT
              value: {{ .Values.inferenceserver.port | quote }}
            - name: SUFFIX
              value: {{ .Values.inferenceserver.suffix | quote }}
            {{- if .Values.rabbitmq.internal }}
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: host
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: password
            {{ else }}
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote}}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ if eq .Values.rabbitmq.existingSecret ""}}rabbitmq-secret {{else}} {{ .Values.rabbitmq.existingSecret }} {{end}}
                  key: {{ if .Values.rabbitmq.secretKeyOverride }} {{ .Values.rabbitmq.secretKeyOverride.username }} {{ else }} username {{ end }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if eq .Values.rabbitmq.existingSecret ""}}rabbitmq-secret {{else}} {{ .Values.rabbitmq.existingSecret }} {{end}}
                  key: {{ if .Values.rabbitmq.secretKeyOverride }} {{ .Values.rabbitmq.secretKeyOverride.password }} {{ else }} password {{ end }}
            {{ end }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.consumer.loglevel | quote }}
            {{- with .Values.consumer.env }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
      volumes:
         - name: dshm
           emptyDir:
              medium: Memory
      {{- with .Values.consumer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.consumer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.consumer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
