{{ $file := . }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: consumer-pod-monitor
spec:
  podMetricsEndpoints:
    - port: {{ .Values.inferenceserver.port | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "vllm.fullname" $file }}-consumer-{{ .name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
