{{ $val := .Values }}
{{ $file := . }}
{{- range .Values.models }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $file.Release.Name }}-consumer-{{ .name }}
  labels:
    {{- include "vllm.labels.consumer" $file | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ $val.consumer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vllm.selectorLabels.consumer" $file | nindent 4 }}
---
{{- end}}
