{{ if and .Values.database.internal (eq .Values.database.existingSecret "") }}
apiVersion: v1
data:
  username: {{ .Values.database.auth.username | b64enc }}
  password: {{ .Values.database.auth.password | b64enc }}
kind: Secret
metadata:
  name: database-secret
type: kubernetes.io/basic-auth
{{ end }}