{{ if and .Values.database.internal }}
apiVersion: v1
data:
  init.sql: |+
    {{ if eq .Values.database.type "mysql" }}
    CREATE TABLE users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, token VARCHAR(255), priority INT NOT NULL, threshold INT NOT NULL, client_type ENUM('chat'));
    {{ end }}
    {{ if eq .Values.database.type "postgresql"}}
    CREATE TYPE client_type as ENUM ('chat');
    CREATE TABLE users (id SERIAL PRIMARY KEY, token VARCHAR(255), priority INT NOT NULL, threshold INT NOT NULL, client_type client_type);
    {{ end }}
    {{- range .Values.tokens }}
    INSERT INTO users (token, priority, threshold, client_type) VALUES ('{{ .token }}', {{ .priority }}, {{ .threshold }}, {{ .client_type }});
    {{- end }}
kind: ConfigMap
metadata:
  name: database-config-map
{{- end }}

