apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vllm.fullname" . }}-sender
spec:
  replicas: {{ .Values.sender.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vllm.fullname" . }}-sender
      app.kubernetes.io/instance: {{ include "vllm.fullname" . }}-sender
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vllm.fullname" . }}-sender
        app.kubernetes.io/instance: {{ include "vllm.fullname" . }}-sender
    spec:
      containers:
        - name: sender
          image: {{ .Values.sender.image.repository }}:{{ .Values.sender.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.sender.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.sender.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          env:
            - name: WORKER_URL
              value: {{ include "vllm.fullname" .}}-consumer
            - name: WORKER_SERVICE
              value: {{ .Release.Name }}-consumer
            - name: WORKER_PORT
              value: {{ .Values.inferenceserver.port | quote}}
            - name: WORKER_NUM
              value: "{{ .Values.sender.replicaCount }}"
            {{ if .Values.rabbitmq.enabled}}
            {{- if .Values.rabbitmq.internal }}
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: host
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: password
            {{ else }}
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote}}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.auth.user | quote}}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.auth.password | quote}}
            {{ end }}
            {{ end }}
            - name: DB_TYPE
              value: {{ .Values.database.type | quote }}
            {{ if .Values.database.internal }}
            - name: DB_HOST
              value: {{ .Release.Name }}-mysql
            {{ else }}
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            {{ end }}
            - name: DB_USER
              value: {{ .Values.database.auth.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.database.auth.password | quote }}
            - name: DB_DATABASE
              value: {{ .Values.database.auth.database | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            {{- with .Values.sender.env }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.sender.resources | nindent 12 }}
