apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-model-storage
  annotations:
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/hook": Skip
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}