{{ if not ( or ( .Values.rabbitmq.internal) (eq .Values.rabbitmq.existingSecret "")) }}
apiVersion: v1
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc }}
  password: {{ .Values.rabbitmq.auth.password | b64enc }}
kind: Secret
metadata:
  name: rabbitmq-secret
type: kubernetes.io/basic-auth
{{ end }}