apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sender
  labels:
    {{- include "vllm.labels.sender" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.sender.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vllm.selectorLabels.sender" . | nindent 4 }}
